### ISSUE TITLE
Program crashes

### ISSUE THREAD

**Issue by Irubataru** [Raspeball/pizzagenerator#1]
After having input the number of people eating Pizza, and their names, the program crashes with the following error message:

```
Traceback (most recent call last):
  File "petterspizzagenerator_v4.py", line 38, in <module>
    orderpizza = ChoosePizza(antall)
  File "petterspizzagenerator_v4.py", line 31, in ChoosePizza
    cpizza = [None]*npizza
TypeError: can't multiply sequence by non-int of type 'float' 
```

**Comment by Raspeball** [comment]
Are you running Python 3.x? I just realised "/" is floor division for int.type in Python 2.x, whereas "/" is true division (for both int at float) in Python 3.x. ChoosePizza assumes (requires, perhaps) "pers" to be an integer, and uses the Python 2.x (2.7, in my case) syntax (i.e. floor division) to determinate the number of pizzas. If you're using Python 3.x,, I think this is the problem. If not, further investigation is required.

**Comment by Irubataru** [comment]
That does indeed seem to be the issue,  using version 2.7 instead of 3.4 fixed the issue, but only after explicitly adding the encoding to the files as described in https://www.python.org/dev/peps/pep-0263/
